 import { Inter } from "next/font/google";
 const inter = Inter({ subsets: ["latin"] });
 require('dotenv').config();
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{boxSizing:'border-box',padding:'0',margin:'0'}}>{children}</body>
    </html>
  );
}
